# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-15 02:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojoninjas_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojo',
            name='name',
            field=models.CharField(default='null', max_length=255),
            preserve_default=False,
        ),
    ]
