# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-15 02:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojoninjas_app', '0002_dojo_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojo',
            name='desc',
            field=models.TextField(default='null'),
            preserve_default=False,
        ),
    ]
